// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyyipfdnmnqhiarszuqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5eWlwZmRubW5xaGlhcnN6dXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2OTI1OTksImV4cCI6MjA1MDI2ODU5OX0.nvTQYsbXDMMmhgQa6YpUiXBRu9ZG3MU5PrOPUhqBygs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);